In [1]:
#from sklearn.preprocessing import LabelBinarizer
#from tensorflow import keras
#from keras.utils import plot_model

#import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import csv
import cv2
import os
from numpy import genfromtxt
import requests
import re

import tensorflow as tf
from tensorflow import keras

from keras import datasets, layers, models
import matplotlib.pyplot as plt


In [11]:
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()
#print(train_images[0][0])

train_images, test_images = train_images / 255.0, test_images / 255.0
print(train_images)

[[[[0.23137255 0.24313725 0.24705882]
   [0.16862745 0.18039216 0.17647059]
   [0.19607843 0.18823529 0.16862745]
   ...
   [0.61960784 0.51764706 0.42352941]
   [0.59607843 0.49019608 0.4       ]
   [0.58039216 0.48627451 0.40392157]]

  [[0.0627451  0.07843137 0.07843137]
   [0.         0.         0.        ]
   [0.07058824 0.03137255 0.        ]
   ...
   [0.48235294 0.34509804 0.21568627]
   [0.46666667 0.3254902  0.19607843]
   [0.47843137 0.34117647 0.22352941]]

  [[0.09803922 0.09411765 0.08235294]
   [0.0627451  0.02745098 0.        ]
   [0.19215686 0.10588235 0.03137255]
   ...
   [0.4627451  0.32941176 0.19607843]
   [0.47058824 0.32941176 0.19607843]
   [0.42745098 0.28627451 0.16470588]]

  ...

  [[0.81568627 0.66666667 0.37647059]
   [0.78823529 0.6        0.13333333]
   [0.77647059 0.63137255 0.10196078]
   ...
   [0.62745098 0.52156863 0.2745098 ]
   [0.21960784 0.12156863 0.02745098]
   [0.20784314 0.13333333 0.07843137]]

  [[0.70588235 0.54509804 0.37647059]
   [0.6

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_9 (Conv2D)           (None, 200, 200, 32)      64        
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 100, 100, 32)     0         
 2D)                                                             
                                                                 
 conv2d_10 (Conv2D)          (None, 100, 100, 64)      2112      
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 50, 50, 64)       0         
 2D)                                                             
                                                                 
 conv2d_11 (Conv2D)          (None, 50, 50, 64)        4160      
                                                                 
 flatten (Flatten)           (None, 160000)           

In [21]:
#letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
#path = "./ASL_CSV/train/"
#df = pd.read_csv("ASL_CSV/train/A/A1.csv", sep = ',')

letter = "A"
num = 2
df = pd.read_csv('./ASL_CSV/train/'+ letter + '/' + letter + str(num) + '.csv', sep=',', header=None)

array = df.to_numpy()
result = array.flatten()
string = ""
for x in result:
    replaced = re.sub("[^0-9 ]+", "", x)
    replaced = re.sub(' +', ' ', replaced).strip()
    string += (" " + replaced)

string = string.split(" ")

string[0] = "A"
df2 = pd.DataFrame(columns=np.arange(40001))
df2.rename(columns={0:"Labels"}, inplace = True)
df2.loc[len(df2)] = string

print(df2.shape[1])
print(df2)


    




40001
  Labels   1   2   3   4   5   6   7   8   9  ... 39991 39992 39993 39994  \
0      A  33  30  31  30  29  30  29  28  28  ...    28    28    26    29   

  39995 39996 39997 39998 39999 40000  
0    29    29    29    29    30    28  

[1 rows x 40001 columns]


In [24]:
def CSV_To_Dataframe(letter):
    path = "./ASL_CSV/train/"
    data = []
    for num in range(101,201):
        df = pd.read_csv(path+letter+'/'+letter+str(num)+'.csv',sep=',',header= None)
        array = df.to_numpy()
        result = array.flatten()
        string = ""
        for x in result:
            replaced = re.sub("[^0-9 ]+", "", x)
            replaced = re.sub(' +', ' ', replaced).strip()
            string += (" " + replaced)
        string = string.split(" ")
        string.pop(0)
        string = [(eval(i)/255) for i in string]
        #print(string)
        data.append(string)
    return data
#print(len(CSV_To_Dataframe("A")))
#print(CSV_To_Dataframe("A"))


In [22]:
master_df = pd.DataFrame(columns = np.arange(100))
#master_df.rename(columns = {0:"Labels"}, inplace = True)
count = 0
def Fill_Dataframe():
    letters = "A" #BCDEFGHIJKLMNOPQRSTUVWXYZ"
    for letter in letters:
        list = CSV_To_Dataframe(letter)
        master_df.loc[len(master_df)] = list
        #count+=1
        #print(count)
    
Fill_Dataframe()
#print(master_df)

In [25]:
test_df = pd.DataFrame(columns = np.arange(100))
#master_df.rename(columns = {0:"Labels"}, inplace = True)
count = 0
def Fill_Dataframe():
    letters = "A" #BCDEFGHIJKLMNOPQRSTUVWXYZ"
    for letter in letters:
        list = CSV_To_Dataframe(letter)
        test_df.loc[len(master_df)] = list
        #count+=1
        #print(count)
    
Fill_Dataframe()
#print(master_df)

In [26]:
print(master_df)

                                                  0   \
0  [0.11764705882352941, 0.11372549019607843, 0.1...   

                                                  1   \
0  [0.12941176470588237, 0.11764705882352941, 0.1...   

                                                  2   \
0  [0.12156862745098039, 0.11764705882352941, 0.1...   

                                                  3   \
0  [0.12156862745098039, 0.10980392156862745, 0.1...   

                                                  4   \
0  [0.12156862745098039, 0.11764705882352941, 0.1...   

                                                  5   \
0  [0.12941176470588237, 0.12156862745098039, 0.1...   

                                                  6   \
0  [0.11764705882352941, 0.11764705882352941, 0.1...   

                                                  7   \
0  [0.12549019607843137, 0.10980392156862745, 0.1...   

                                                  8   \
0  [0.12941176470588237, 0.1176470588235

In [33]:

data_a = master_df
labels = ['a']*100

model = models.Sequential()
model.add(layers.Conv2D(32, (1, 1), activation='relu', input_shape=(200, 200, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (1, 1), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (1, 1), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

#model.summary()

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(master_df, labels, epochs=10, 
                    validation_data=(test_df, labels))

ValueError: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, (<class 'list'> containing values of types {"<class 'str'>"})